[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd api-autenticacion && npm install"]

[phases.build]
cmds = ["cd api-autenticacion && npm run build || echo 'No build script found, skipping...'"]

[start]
cmd = "cd api-autenticacion && npm start"
