services:
  - type: web
    name: sae-api
    env: node
    buildCommand: cd api-autenticacion && npm install
    startCommand: cd api-autenticacion && npm start
    envVars:
      - key: NODE_ENV
        value: production
