-- MySQL Script generated by MySQL Workbench
-- Sun Jun  8 12:44:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sae_software
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sae_software
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sae_software` DEFAULT CHARACTER SET utf8 ;
USE `sae_software` ;

-- -----------------------------------------------------
-- Table `sae_software`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Cliente` (
  `id_Cliente_documento` VARCHAR(20) NOT NULL,
  `numero_identidad` VARCHAR(20) NULL,
  `nombres` VARCHAR(150) NULL,
  `apellidos` VARCHAR(150) NULL,
  `telefono` VARCHAR(20) NULL,
  `correoElectronico` VARCHAR(250) NULL,
  PRIMARY KEY (`id_Cliente_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Vehiculo` (
  `id_Placa` VARCHAR(10) NOT NULL,
  `id_Cliente_documento` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  INDEX `fk_Vehiculo_Cliente1_idx` (`id_Cliente_documento` ASC),
  PRIMARY KEY (`id_Placa`),
  CONSTRAINT `fk_Vehiculo_Cliente1`
    FOREIGN KEY (`id_Cliente_documento`)
    REFERENCES `sae_software`.`Cliente` (`id_Cliente_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Plaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Plaza` (
  `id_Plaza` INT NOT NULL,
  `estado` ENUM('libre', 'ocupado') NULL,
  PRIMARY KEY (`id_Plaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Empleado` (
  `id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(200) NOT NULL,
  `nombreUsuario` VARCHAR(150) NOT NULL,
  `numeroDocumento` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(250) NOT NULL,
  `tipoUsuario` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Estacionamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Estacionamiento` (
  `id_Estacionamiento` INT NOT NULL,
  `id_Plaza` INT NOT NULL,
  `nombreEstacionamiento` VARCHAR(100) NULL,
  `capacidad` INT NULL,
  PRIMARY KEY (`id_Estacionamiento`),
  INDEX `fk_Estacionamiento_Plaza1_idx` (`id_Plaza` ASC),
  CONSTRAINT `fk_Estacionamiento_Plaza1`
    FOREIGN KEY (`id_Plaza`)
    REFERENCES `sae_software`.`Plaza` (`id_Plaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Ticket` (
  `id_Ticket` INT NOT NULL AUTO_INCREMENT,
  `id_Placa` VARCHAR(10) NOT NULL,
  `id_Plaza` INT NOT NULL,
  `id_Estacionamiento` INT NOT NULL,
  `id_Empleado_documento` VARCHAR(20) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `horaIngreso` TIME NOT NULL,
  `fechaSalida` DATE NOT NULL,
  `horaSalida` TIME NOT NULL,
  `duracion` DATETIME NOT NULL,
  PRIMARY KEY (`id_Ticket`),
  INDEX `fk_Ticket_Vehiculo_idx` (`id_Placa` ASC),
  INDEX `fk_Ticket_Plaza1_idx` (`id_Plaza` ASC),
  INDEX `fk_Ticket_Empleado1_idx` (`id_Empleado_documento` ASC),
  INDEX `fk_Ticket_Estacionamiento1_idx` (`id_Estacionamiento` ASC),
  CONSTRAINT `fk_Ticket_Vehiculo`
    FOREIGN KEY (`id_Placa`)
    REFERENCES `sae_software`.`Vehiculo` (`id_Placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Plaza1`
    FOREIGN KEY (`id_Plaza`)
    REFERENCES `sae_software`.`Plaza` (`id_Plaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Empleado1`
    FOREIGN KEY (`id_Empleado_documento`)
    REFERENCES `sae_software`.`Empleado` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Estacionamiento1`
    FOREIGN KEY (`id_Estacionamiento`)
    REFERENCES `sae_software`.`Estacionamiento` (`id_Estacionamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Incidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Incidencias` (
  `id_Incidencias` INT NOT NULL AUTO_INCREMENT,
  `id_Ticket` INT NOT NULL,
  `id_Empleado_documento` VARCHAR(20) NOT NULL,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_Incidencias`),
  INDEX `fk_Incidencias_Ticket1_idx` (`id_Ticket` ASC),
  INDEX `fk_Incidencias_Empleado1_idx` (`id_Empleado_documento` ASC),
  CONSTRAINT `fk_Incidencias_Ticket1`
    FOREIGN KEY (`id_Ticket`)
    REFERENCES `sae_software`.`Ticket` (`id_Ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencias_Empleado1`
    FOREIGN KEY (`id_Empleado_documento`)
    REFERENCES `sae_software`.`Empleado` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sae_software`.`Asignacion_Empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sae_software`.`Asignacion_Empleo` (
  `id_Asignacion_Empleo` INT NOT NULL,
  `id_Empleado_documento` VARCHAR(20) NOT NULL,
  `id_Estacionamiento` INT NOT NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NULL,
  PRIMARY KEY (`id_Asignacion_Empleo`),
  INDEX `fk_Asignacion_Empleo_Empleado1_idx` (`id_Empleado_documento` ASC),
  INDEX `fk_Asignacion_Empleo_Estacionamiento1_idx` (`id_Estacionamiento` ASC),
  CONSTRAINT `fk_Asignacion_Empleo_Empleado1`
    FOREIGN KEY (`id_Empleado_documento`)
    REFERENCES `sae_software`.`Empleado` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Empleo_Estacionamiento1`
    FOREIGN KEY (`id_Estacionamiento`)
    REFERENCES `sae_software`.`Estacionamiento` (`id_Estacionamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
